name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]  # Updated to 1.23

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race ./...

    - name: Build
      run: go build -v ./...

